#!/usr/bin/env python

import rospy
from script_executor.script_executor import ScriptExecutor

if __name__ == "__main__":
    rospy.init_node('script_executor')

    while not rospy.is_shutdown():
        try:
            script_executor = ScriptExecutor()
            rospy.spin()
        except Exception as e:
            rospy.logerr('[script_executor] Exception: %s', str(e))
