- "$example.bash & disown"
- "$example_with_argument.bash #"
- "$example_with_arguments.bash ABC #"
- "$example_with_arguments.bash # EFG"
- "killall roslaunch"
- "killall rosmaster"
- "rosnode kill --all"
- "reboot"
- "shutdown -P now"